import arcpy, os
... 
... arcpy.env.workspace = ws = r"E:\data cita\Teluk bone\map"
... 
... mxd_list = arcpy.ListFiles("*.mxd")
... 
... for mxd in mxd_list:
...     
...     current_mxd = arcpy.mapping.MapDocument(os.path.join(ws, mxd))
...     jpeg_name = mxd[:-4] + ".jpeg"
...     arcpy.mapping.ExportToJPEG(current_mxd, jpeg_name)
...  
... del mxd_list
... 
